// <auto-generated />
using System;
using ApiPruebasDIF.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPruebasDIF.Migrations
{
    [DbContext(typeof(DBContexts))]
    [Migration("20231211155451_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ApiPruebasDIF.DB.Models.UnidadesIngresos", b =>
                {
                    b.Property<int>("IdUnidades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Recaudado")
                        .HasColumnType("REAL");

                    b.Property<string>("Rubro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUnidades");

                    b.ToTable("UnidadesIngreso");
                });

            modelBuilder.Entity("ApiPruebasDIF.DB.Models.UnidadesPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cve_Rubro_Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Egreso_Imp_Comprometido")
                        .HasColumnType("REAL");

                    b.Property<double?>("Egreso_Imp_Devengado")
                        .HasColumnType("REAL");

                    b.Property<double?>("Egreso_Imp_Ejercido")
                        .HasColumnType("REAL");

                    b.Property<double?>("Egreso_Imp_Pagado")
                        .HasColumnType("REAL");

                    b.Property<double?>("Egreso_Imp_Reduccion")
                        .HasColumnType("REAL");

                    b.Property<double?>("Egreso_Imp_aprobado")
                        .HasColumnType("REAL");

                    b.Property<double?>("Ejecutado")
                        .HasColumnType("REAL");

                    b.Property<int>("Id_Ppto")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Imp_Comp_Dev_Eje_Pagado")
                        .HasColumnType("REAL");

                    b.Property<int?>("Num_Mes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("egreso_Imp_Ampliacion")
                        .HasColumnType("REAL");

                    b.Property<double?>("imp_Modificado")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UnidadesPresupuesto");
                });
#pragma warning restore 612, 618
        }
    }
}
